### ISSUE TITLE
Nice job :P

### ISSUE THREAD

**Issue by eerimoq** [qchateau/cbitstruct#1]
How much faster then the Python implementation is it? Any drawbacks/limitations?

**Comment by qchateau** [comment]
Hi,

Sorry you discovered my shameless copy like this. I intended to write a minimal readme presenting this project, and its pros and cons compared to yours.

Here are the limitations:
- Requires python 3.6+
- Elements cannot be more than 64 bits wide except for padding
- Packing numbers too big for their packed size is not detected
- Error handling is poor. What you get is an exception with a very vague error message
- I tried to make this code endian agnostic but to be fair it would be a surprise if it worked on big-endian architectures. I have absolutely no idea how to verify this code or big-endian architectures...

I may be able to extend support for earlier versions of python, but I don't intend to spend too much time to support old python version, so I have no target about this.

The 64bits limitation is probably here to stay. I may remove this limitation for text and raw, but it is not a priority, and I won't do it if the runtime cost is noticeable.

Error handling can always be improved, the condition I put on this is: don't slow runtime.

Currently the C implementation is 10 to 20 times faster. I will probably reach 30 when I'm done removing what's left of python code.

There are a few corner cases that seem to be handled incorrectly by `bitstruct` (and my lib as well). For now I made sure my implementation passes your unit tests, and behaves like yours using randomly generated data and formats. When I'm happy about my code, I'll probably focus on identifying corner cases. I'll keep you up to date about my "discoveries" in this area.

**Comment by eerimoq** [comment]
No problem, I just searched for bitstruct here on Github to find projects using it, and I'm glad you are implementing a version of it in C for performance reasons.

Looking forward to the end result. I can add a link to this project in the bitstruct readme to help others find it, if you want that.

Let me know about the problems, and let's keep both versions in sync so users can use cbitstruct as a drop in replacement of bitstruct if they prefer.

**Comment by qchateau** [comment]
Yes that was what I had in mind: I will try to make my API 100% compliant with yours so that people can use `bitstruct` to develop and debug easily, and switch to a faster `cbitstruct` when they are ready to give up ease of use for performance.

Will keep you updated

**Comment by eerimoq** [comment]
Hello again!

I just want to let you know that I started implementing bitstruct as a C-extension a few months ago , similar to yours. I couldn't resist continue working on it after finding your repository. =)

Currently my implementation only supports the `pack()` and `unpack()` functions, with a few limitations (similar to yours). No compiled formats are supported. Future will tell if I'll continue on my implementation, I likely will, and probably release it fairly soon.

**Comment by qchateau** [comment]
Hello, just letting you know I released a version 1.0.0, available on pypi. I managed to remove a few limitations, everything is in the README :)
